language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - "node_modules"
install:
    - cd s3-to-rds && npm install
before_deploy:
    - ls -la
    - cd s3-to-rds && npm install
    - bash -ex scripts/undeploy.sh
script:
    - echo "script"
deploy:
    provider: script
    script: bash -ex scripts/deploy.sh
    on:
        branch: db
        