language: node_js
node_js:
    - "lts/*"
before_install:
    - echo "before_install"
install:
    - npm install
script:
    - echo "script"
deploy:
    provider: script
    script: cicd/deploy.sh
    on:
        branch: master
        