language: node_js
node_js:
    - 8.10
cache:
    directories:
        - "node_modules"
        - "s3-to-rds/node_modules"
install:
    - pushd s3-to-rds
    - npm install
    - popd
    - npm install
# before_deploy:
#     - bash -ex scripts/undeploy.sh
deploy:
    skip_cleanup: true
    provider: script
    script: bash -ex scripts/deploy.sh
    on:
        all_branches: true