language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - "node_modules"
before_deploy:
    - npm install -g serverless
script:
    - echo "script"
deploy:
    provider: script
    script: bash -ex scripts/deploy.sh
    on:
        branch: master
        