language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - "node_modules"
install:
    - cd s3-to-rds && npm install
before_deploy:
    - cd s3-to-rds && npm install
    - bash -ex npm run undeploy
script:
    - echo "script"
deploy:
    provider: script
    script: bash -ex npm run deploy
    on:
        branch: db
        