language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - "node_modules"
        - "s3-to-rds/node_modules"
install:
    - pushd s3-to-rds
    - npm install
    - popd
before_deploy:
    - pushd s3-to-rds
    - npm install
    - popd
    - bash -ex scripts/undeploy.sh
script:
    - echo "script"
deploy:
    provider: script
    script: bash -ex scripts/deploy.sh
    on:
        branch: db
        