language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - "node_modules"
before_install:
    - echo "before_install"
install:
    - npm install
script:
    - echo "script"
deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        branch: master
        